// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_rHsI6Ori_m5Da3g7ZwAEwaCuf3ewHwU',
    appId: '1:70967126082:web:f3ca802e3ceddb351165db',
    messagingSenderId: '70967126082',
    projectId: 'app-lcc-cbfa9',
    authDomain: 'app-lcc-cbfa9.firebaseapp.com',
    storageBucket: 'app-lcc-cbfa9.firebasestorage.app',
    measurementId: 'G-6X5XPR3GP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY_iaKRVeCj5xDP64ad7FZGrCWUQgS2CY',
    appId: '1:70967126082:android:15adb01ca0d2a6c21165db',
    messagingSenderId: '70967126082',
    projectId: 'app-lcc-cbfa9',
    storageBucket: 'app-lcc-cbfa9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4x27TawhzHV3Gc1fXbHdn7dAWmXuwsrw',
    appId: '1:70967126082:ios:8738b263adfcfe2c1165db',
    messagingSenderId: '70967126082',
    projectId: 'app-lcc-cbfa9',
    storageBucket: 'app-lcc-cbfa9.firebasestorage.app',
    iosBundleId: 'com.example.appLcc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4x27TawhzHV3Gc1fXbHdn7dAWmXuwsrw',
    appId: '1:70967126082:ios:8738b263adfcfe2c1165db',
    messagingSenderId: '70967126082',
    projectId: 'app-lcc-cbfa9',
    storageBucket: 'app-lcc-cbfa9.firebasestorage.app',
    iosBundleId: 'com.example.appLcc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_rHsI6Ori_m5Da3g7ZwAEwaCuf3ewHwU',
    appId: '1:70967126082:web:e542d9f6a889a0c21165db',
    messagingSenderId: '70967126082',
    projectId: 'app-lcc-cbfa9',
    authDomain: 'app-lcc-cbfa9.firebaseapp.com',
    storageBucket: 'app-lcc-cbfa9.firebasestorage.app',
    measurementId: 'G-Y8GQ357R95',
  );
}
